### ISSUE TITLE
What does the manager app do?

### ISSUE THREAD

**Issue by ZeeshanPereira** [heycarsten/lcbo-api#23]
Hi, I'd like to know what the manager app does or was intended to do, its features, and etc. I tried following your instructions to run it, but it does not work - probably because it is outdated. Leaving the errors here, just in case anything can be done. Thanks!

npm install does not build properly:

WARN invalid config loglevel="notice"
Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/win32-x64-node-10.15/binding.node

node-sass@2.1.1 postinstall C:\Users\zeesh\OneDrive\Desktop\Gettit\manager\node_modules\node-sass
node scripts/build.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'C:\Users\zeesh\OneDrive\Desktop\Gettit\manager\node_modules\node-sass\node_modules\pangyp\bin\node-gyp'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
Build failed
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ember-cli@0.2.0 had bundled packages that do not match the required version(s). They have been replaced with non-bundled versions.

And then running ember server gives:
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at evalmachine.<anonymous>:44:31
    at Object.<anonymous> (C:\Users\zeesh\OneDrive\Desktop\Gettit\manager\node_modules\ember-cli\node_modules\configstore\node_modules\graceful-fs\fs.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)

**Comment by craftdelivery** [comment]
There was a documentation web app as well as admin features. The site is down and was most likely configured for a specific case. The scraper and rails api are the main things worth looking at
